/*
 * Login page
 */


const char* loginIndex = 
"<style>"
".center_center{display:grid;justify-content:center;align-content:center;}"
"tbody{margin:1em}"
"input{border-radius: .25em;min-height: 5vh;height: 5vh;text-align: center;}"
"input::selection {border-color: red;background: grey;}"
"html{background-color:#181a1b;width:100vw;height:100vh;display:grid;justify-content:center;align-content:center;}"
"tr{display:grid;justify-content:center;margin:.25em;}"
"td{display:grid;justify-content:center;}"
"</style>"
 "<form name='loginForm'>"
    "<table bgcolor='A09F9F' class='center_center' align='center' style='width:30vw;height:auto;'>"
        "<tr>"
            "<td colspan=2>"
                "<center><font size=4><b>Wrigglyt ESP32 Login Page</b></font></center>"
        "</tr>"
        "<tr>"
        "<td><input type='text' placeholder='Username' size=25 name='userid'></td>"
        "</tr>"
        "<tr>"
            "<td><input type='Password' placeholder='Password' size=25 name='pwd'></td>"
        "</tr>"
        "<tr>"
            "<td><input type='submit' onclick='check(this.form)' value='Login' style='width:10vw;'></td>"
        "</tr>"
    "</table>"
"</form>"
"<script>"
    "function check(form)"
    "{"
    "if(form.userid.value=='admin' && form.pwd.value=='admin')"
    "{"
    "window.open('/serverIndex')"
    "}"
    "else"
    "{"
    " alert('Error Password or Username')/*displays error message*/"
    "}"
    "}"
"</script>";