/*
 * Server Index Page
 */
const char* serverIndex = 
"<script src='https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js'></script>"
"<style>"
"progress{background-color:cadetblue;border-color:cadetblue;height:5vh;width:40vw;border-radius:10em;}"
"progress::-webkit-progress-value{color:green;}"
"progress::-moz-progress-value{color:green;}"
"html{background-color:#181a1b;width:100vw;height:100vh;display:grid;justify-content:center;align-content:center;}"
".center_center{display:grid;justify-content:center;align-content:center;justify-items:center;}"
"tbody{display:grid;justify-content:center;align-content:center;}"
"input{border-radius:.25em;min-height:5vh;height:10vh;text-align: center;}"
"input::selection{border-color: red;background: grey;}"
"tr{display:grid;justify-content:center;}"
"td{display:grid;justify-content:center;}"
"form{display:grid;justify-content:center;width:40vw;height:50vh;}"
".file{border: 2px solid grey;padding: 1em 1em 1em 1em;height:30vh;width:25vw;display:grid;justify-content:center;align-content:center;}"
"</style>"
"<div class='center_center'>"
"<form method='POST' action='#' enctype='multipart/form-data' id='upload_form'>"
   "<input type='file' name='update' class='file'>"
        "<input type='submit' value='Update' >"
    "</form>"
 "<div id='prgtitle'>0%</div>"
 "<progress value='0' max='100' id='prg'>0%</progress>"
"</div>"
 "<script>"
  "$('form').submit(function(e){"
  "e.preventDefault();"
  "var form = $('#upload_form')[0];"
  "var data = new FormData(form);"
  " $.ajax({"
  "url: '/update',"
  "type: 'POST',"
  "data: data,"
  "contentType: false,"
  "processData:false,"
  "xhr: function() {"
  "var xhr = new window.XMLHttpRequest();"
  "xhr.upload.addEventListener('progress', function(evt) {"
  "if (evt.lengthComputable) {"
  "var per = evt.loaded / evt.total;"
  "$('#prg').val(Math.round(per*100));"
  "$('#prgtitle').html('progress: ' + Math.round(per*100) + '%');"
  "}"
  "}, false);"
  "return xhr;"
  "},"
  "success:function(d, s) {"
  "console.log('success!');" 
  "$('#upload_form').css('border','2px solid green');"
 "},"
 "error: function (a, b, c) {"
 "}"
 "});"
 "});"
 "</script>";

const char* oldserverIndex = 
"<script src='https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js'></script>"
"<form method='POST' action='#' enctype='multipart/form-data' id='upload_form'>"
   "<input type='file' name='update'>"
        "<input type='submit' value='Update'>"
    "</form>"
 "<div id='prg'>progress: 0%</div>"
 "<script>"
  "$('form').submit(function(e){"
  "e.preventDefault();"
  "var form = $('#upload_form')[0];"
  "var data = new FormData(form);"
  " $.ajax({"
  "url: '/update',"
  "type: 'POST',"
  "data: data,"
  "contentType: false,"
  "processData:false,"
  "xhr: function() {"
  "var xhr = new window.XMLHttpRequest();"
  "xhr.upload.addEventListener('progress', function(evt) {"
  "if (evt.lengthComputable) {"
  "var per = evt.loaded / evt.total;"
  "$('#prg').html('progress: ' + Math.round(per*100) + '%');"
  "}"
  "}, false);"
  "return xhr;"
  "},"
  "success:function(d, s) {"
  "console.log('success!')" 
 "},"
 "error: function (a, b, c) {"
 "}"
 "});"
 "});"
 "</script>";